import type { CatalogEntry } from './types';

/**
 * Pre-populated subscription catalog with 200+ services.
 * Prices are in cents and reflect typical US pricing as of 2026.
 */
export const CATALOG_ENTRIES: readonly CatalogEntry[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // ENTERTAINMENT (55 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'netflix-standard',
    name: 'Netflix Standard',
    defaultPrice: 1549,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
    cancellationUrl: 'https://www.netflix.com/cancelplan',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Membership. Access continues until billing period ends.',
  },
  {
    id: 'netflix-premium',
    name: 'Netflix Premium',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
    cancellationUrl: 'https://www.netflix.com/cancelplan',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Membership. Access continues until billing period ends.',
  },
  {
    id: 'netflix-standard-ads',
    name: 'Netflix Standard with Ads',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'netflix',
    url: 'https://www.netflix.com',
    cancellationUrl: 'https://www.netflix.com/cancelplan',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Membership. Access continues until billing period ends.',
  },
  {
    id: 'spotify-premium',
    name: 'Spotify Premium',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
    cancellationUrl: 'https://www.spotify.com/account/subscription/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel Premium. Reverts to free tier.',
  },
  {
    id: 'spotify-duo',
    name: 'Spotify Premium Duo',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
    cancellationUrl: 'https://www.spotify.com/account/subscription/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel Premium. Reverts to free tier.',
  },
  {
    id: 'spotify-family',
    name: 'Spotify Premium Family',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'spotify',
    url: 'https://www.spotify.com',
    cancellationUrl: 'https://www.spotify.com/account/subscription/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel Premium. All family members revert to free.',
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube',
    url: 'https://www.youtube.com/premium',
    cancellationUrl: 'https://www.youtube.com/paid_memberships',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Purchases and memberships > Manage membership > Deactivate.',
  },
  {
    id: 'youtube-premium-family',
    name: 'YouTube Premium Family',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube',
    url: 'https://www.youtube.com/premium',
    cancellationUrl: 'https://www.youtube.com/paid_memberships',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Purchases and memberships > Manage membership > Deactivate.',
  },
  {
    id: 'youtube-music',
    name: 'YouTube Music Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube-music',
    url: 'https://music.youtube.com',
    cancellationUrl: 'https://www.youtube.com/paid_memberships',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Purchases and memberships > Manage membership > Deactivate.',
  },
  {
    id: 'disney-plus',
    name: 'Disney+ (No Ads)',
    defaultPrice: 1599,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'disney-plus',
    url: 'https://www.disneyplus.com',
    cancellationUrl: 'https://www.disneyplus.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel Subscription. Access continues until billing period ends.',
  },
  {
    id: 'disney-plus-ads',
    name: 'Disney+ (With Ads)',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'disney-plus',
    url: 'https://www.disneyplus.com',
    cancellationUrl: 'https://www.disneyplus.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel Subscription. Access continues until billing period ends.',
  },
  {
    id: 'hulu',
    name: 'Hulu (With Ads)',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'hulu',
    url: 'https://www.hulu.com',
    cancellationUrl: 'https://secure.hulu.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Your Subscription. Access continues until billing period ends.',
  },
  {
    id: 'hulu-no-ads',
    name: 'Hulu (No Ads)',
    defaultPrice: 1899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'hulu',
    url: 'https://www.hulu.com',
    cancellationUrl: 'https://secure.hulu.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Your Subscription. Access continues until billing period ends.',
  },
  {
    id: 'hbo-max',
    name: 'Max (Ad-Free)',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
    cancellationUrl: 'https://www.max.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel Subscription. If subscribed via app store, cancel there.',
  },
  {
    id: 'hbo-max-ads',
    name: 'Max (With Ads)',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
    cancellationUrl: 'https://www.max.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel Subscription. If subscribed via app store, cancel there.',
  },
  {
    id: 'hbo-max-ultimate',
    name: 'Max Ultimate (4K)',
    defaultPrice: 2099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'max',
    url: 'https://www.max.com',
    cancellationUrl: 'https://www.max.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel Subscription. If subscribed via app store, cancel there.',
  },
  {
    id: 'amazon-prime-video',
    name: 'Amazon Prime Video',
    defaultPrice: 899,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'prime-video',
    url: 'https://www.amazon.com/primevideo',
    cancellationUrl: 'https://www.amazon.com/gp/video/settings/subscriptions',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Prime Video > Account & Settings > Channels. If bundled with Prime, cancel the full membership.',
  },
  {
    id: 'apple-tv-plus',
    name: 'Apple TV+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-tv',
    url: 'https://tv.apple.com',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple TV+ > Cancel. Also works from Apple devices.',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-music',
    url: 'https://music.apple.com',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple Music > Cancel.',
  },
  {
    id: 'apple-music-family',
    name: 'Apple Music Family',
    defaultPrice: 1699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple-music',
    url: 'https://music.apple.com',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple Music > Cancel.',
  },
  {
    id: 'apple-one-individual',
    name: 'Apple One Individual',
    defaultPrice: 1995,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple One > Cancel. Individual services can be kept separately.',
  },
  {
    id: 'apple-one-family',
    name: 'Apple One Family',
    defaultPrice: 2595,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple One > Cancel. Individual services can be kept separately.',
  },
  {
    id: 'apple-one-premier',
    name: 'Apple One Premier',
    defaultPrice: 3795,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'apple',
    url: 'https://www.apple.com/apple-one',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple One > Cancel. Individual services can be kept separately.',
  },
  {
    id: 'peacock-premium',
    name: 'Peacock Premium',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'peacock',
    url: 'https://www.peacocktv.com',
    cancellationUrl: 'https://www.peacocktv.com/account/plans',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Plans > Cancel Plan. Access continues until billing period ends.',
  },
  {
    id: 'peacock-premium-plus',
    name: 'Peacock Premium Plus',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'peacock',
    url: 'https://www.peacocktv.com',
    cancellationUrl: 'https://www.peacocktv.com/account/plans',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Plans > Cancel Plan. Access continues until billing period ends.',
  },
  {
    id: 'paramount-plus',
    name: 'Paramount+ (Essential)',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'paramount-plus',
    url: 'https://www.paramountplus.com',
    cancellationUrl: 'https://www.paramountplus.com/account/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Subscription. Access continues until billing period ends.',
  },
  {
    id: 'paramount-plus-premium',
    name: 'Paramount+ with Showtime',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'paramount-plus',
    url: 'https://www.paramountplus.com',
    cancellationUrl: 'https://www.paramountplus.com/account/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Subscription. Access continues until billing period ends.',
  },
  {
    id: 'discovery-plus',
    name: 'Discovery+',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'discovery-plus',
    url: 'https://www.discoveryplus.com',
    cancellationUrl: 'https://www.discoveryplus.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll Premium',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'crunchyroll',
    url: 'https://www.crunchyroll.com',
    cancellationUrl: 'https://www.crunchyroll.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account Settings > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'crunchyroll-mega',
    name: 'Crunchyroll Mega Fan',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'crunchyroll',
    url: 'https://www.crunchyroll.com',
    cancellationUrl: 'https://www.crunchyroll.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account Settings > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'tidal-hifi',
    name: 'TIDAL HiFi',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'tidal',
    url: 'https://tidal.com',
    cancellationUrl: 'https://tidal.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription.',
  },
  {
    id: 'tidal-hifi-plus',
    name: 'TIDAL HiFi Plus',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'tidal',
    url: 'https://tidal.com',
    cancellationUrl: 'https://tidal.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription.',
  },
  {
    id: 'amazon-music-unlimited',
    name: 'Amazon Music Unlimited',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'amazon-music',
    url: 'https://music.amazon.com',
    cancellationUrl: 'https://www.amazon.com/music/settings',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Amazon Music Settings > Cancel subscription. Multiple confirmation steps required.',
  },
  {
    id: 'deezer-premium',
    name: 'Deezer Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'deezer',
    url: 'https://www.deezer.com',
    cancellationUrl: 'https://www.deezer.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Manage my subscription > Cancel. Reverts to free tier.',
  },
  {
    id: 'pandora-plus',
    name: 'Pandora Plus',
    defaultPrice: 549,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'pandora',
    url: 'https://www.pandora.com',
    cancellationUrl: 'https://www.pandora.com/account/manage',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. Reverts to free ad-supported tier.',
  },
  {
    id: 'pandora-premium',
    name: 'Pandora Premium',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'pandora',
    url: 'https://www.pandora.com',
    cancellationUrl: 'https://www.pandora.com/account/manage',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. Reverts to free ad-supported tier.',
  },
  {
    id: 'siriusxm',
    name: 'SiriusXM Streaming',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'siriusxm',
    url: 'https://www.siriusxm.com',
    cancellationUrl: 'https://www.siriusxm.com/manage-subscription',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Must call or use live chat to cancel. Retention agents will offer discounts. No self-service online cancellation.',
  },
  {
    id: 'audible-premium',
    name: 'Audible Premium Plus',
    defaultPrice: 1495,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'audible',
    url: 'https://www.audible.com',
    cancellationUrl: 'https://www.audible.com/account/cancel-membership',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account Details > Cancel membership. Multiple retention screens. Purchased audiobooks are kept.',
  },
  {
    id: 'audible-plus',
    name: 'Audible Plus',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'audible',
    url: 'https://www.audible.com',
    cancellationUrl: 'https://www.audible.com/account/cancel-membership',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account Details > Cancel membership. Multiple retention screens. Purchased audiobooks are kept.',
  },
  {
    id: 'kindle-unlimited',
    name: 'Kindle Unlimited',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'kindle',
    url: 'https://www.amazon.com/kindleunlimited',
    cancellationUrl: 'https://www.amazon.com/kindle-dbs/hz/subscribe/ku/manageSubscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Kindle Unlimited > Manage Subscription > Cancel. Borrowed books are returned.',
  },
  {
    id: 'scribd',
    name: 'Scribd',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'scribd',
    url: 'https://www.scribd.com',
    cancellationUrl: 'https://www.scribd.com/account-settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account Settings > Subscription > Cancel subscription.',
  },
  {
    id: 'xbox-game-pass-core',
    name: 'Xbox Game Pass Core',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'xbox',
    url: 'https://www.xbox.com/gamepass',
    cancellationUrl: 'https://account.microsoft.com/services',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Microsoft Account > Services & subscriptions > Cancel. Auto-renewal can be toggled off.',
  },
  {
    id: 'xbox-game-pass-ultimate',
    name: 'Xbox Game Pass Ultimate',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'xbox',
    url: 'https://www.xbox.com/gamepass',
    cancellationUrl: 'https://account.microsoft.com/services',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Microsoft Account > Services & subscriptions > Cancel. Auto-renewal can be toggled off.',
  },
  {
    id: 'playstation-plus-essential',
    name: 'PlayStation Plus Essential',
    defaultPrice: 7999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'playstation',
    url: 'https://www.playstation.com/ps-plus',
    cancellationUrl: 'https://store.playstation.com/en-us/latest',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Account Management > Account Information > PlayStation Subscriptions > Turn Off Auto-Renew.',
  },
  {
    id: 'playstation-plus-premium',
    name: 'PlayStation Plus Premium',
    defaultPrice: 17999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'playstation',
    url: 'https://www.playstation.com/ps-plus',
    cancellationUrl: 'https://store.playstation.com/en-us/latest',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Account Management > Account Information > PlayStation Subscriptions > Turn Off Auto-Renew.',
  },
  {
    id: 'nintendo-switch-online',
    name: 'Nintendo Switch Online',
    defaultPrice: 3999,
    billingCycle: 'annual',
    category: 'entertainment',
    iconKey: 'nintendo',
    url: 'https://www.nintendo.com/switch/online',
    cancellationUrl: 'https://accounts.nintendo.com/shop/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Nintendo Account > Shop Menu > Nintendo Switch Online > Turn Off Automatic Renewal.',
  },
  {
    id: 'twitch-turbo',
    name: 'Twitch Turbo',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'twitch',
    url: 'https://www.twitch.tv/turbo',
    cancellationUrl: 'https://www.twitch.tv/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Subscriptions page > Turbo > Do not Renew.',
  },
  {
    id: 'espn-plus',
    name: 'ESPN+',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'espn',
    url: 'https://plus.espn.com',
    cancellationUrl: 'https://plus.espn.com/account/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > ESPN+ Subscription > Cancel Subscription.',
  },
  {
    id: 'fubo-pro',
    name: 'FuboTV Pro',
    defaultPrice: 7999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'fubo',
    url: 'https://www.fubo.tv',
    cancellationUrl: 'https://www.fubo.tv/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Subscription & Billing > Cancel Subscription.',
  },
  {
    id: 'youtube-tv',
    name: 'YouTube TV',
    defaultPrice: 7299,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'youtube-tv',
    url: 'https://tv.youtube.com',
    cancellationUrl: 'https://tv.youtube.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Membership > Pause or cancel membership > Cancel membership.',
  },
  {
    id: 'sling-tv-orange',
    name: 'Sling TV Orange',
    defaultPrice: 4000,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'sling',
    url: 'https://www.sling.com',
    cancellationUrl: 'https://www.sling.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel subscription. Multiple retention screens before final cancel.',
  },
  {
    id: 'mubi',
    name: 'MUBI',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'mubi',
    url: 'https://mubi.com',
    cancellationUrl: 'https://mubi.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel subscription.',
  },
  {
    id: 'criterion-channel',
    name: 'Criterion Channel',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'criterion',
    url: 'https://www.criterionchannel.com',
    cancellationUrl: 'https://www.criterionchannel.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel Plan.',
  },
  {
    id: 'shudder',
    name: 'Shudder',
    defaultPrice: 699,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'shudder',
    url: 'https://www.shudder.com',
    cancellationUrl: 'https://www.shudder.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'starz',
    name: 'STARZ',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'entertainment',
    iconKey: 'starz',
    url: 'https://www.starz.com',
    cancellationUrl: 'https://www.starz.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel subscription. If via app store, cancel there.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PRODUCTIVITY (42 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'chatgpt',
    url: 'https://chat.openai.com',
    cancellationUrl: 'https://chat.openai.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel plan. Access continues until billing period ends.',
  },
  {
    id: 'chatgpt-pro',
    name: 'ChatGPT Pro',
    defaultPrice: 20000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'chatgpt',
    url: 'https://chat.openai.com',
    cancellationUrl: 'https://chat.openai.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel plan. Access continues until billing period ends.',
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'claude',
    url: 'https://claude.ai',
    cancellationUrl: 'https://claude.ai/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel plan. Access continues until billing period ends.',
  },
  {
    id: 'claude-max',
    name: 'Claude Max',
    defaultPrice: 10000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'claude',
    url: 'https://claude.ai',
    cancellationUrl: 'https://claude.ai/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel plan. Access continues until billing period ends.',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot Pro',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'github',
    url: 'https://github.com/features/copilot',
    cancellationUrl: 'https://github.com/settings/billing/summary',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Plans and usage > Cancel Copilot.',
  },
  {
    id: 'microsoft-365-personal',
    name: 'Microsoft 365 Personal',
    defaultPrice: 9999,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'microsoft-365',
    url: 'https://www.microsoft.com/microsoft-365',
    cancellationUrl: 'https://account.microsoft.com/services',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Microsoft Account > Services & subscriptions > Cancel. Turn off recurring billing.',
  },
  {
    id: 'microsoft-365-family',
    name: 'Microsoft 365 Family',
    defaultPrice: 12999,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'microsoft-365',
    url: 'https://www.microsoft.com/microsoft-365',
    cancellationUrl: 'https://account.microsoft.com/services',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Microsoft Account > Services & subscriptions > Cancel. Turn off recurring billing.',
  },
  {
    id: 'google-one-100gb',
    name: 'Google One 100GB',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-one',
    url: 'https://one.google.com',
    cancellationUrl: 'https://one.google.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Google One > Settings > Cancel membership. Storage reverts to 15GB free.',
  },
  {
    id: 'google-one-2tb',
    name: 'Google One 2TB',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-one',
    url: 'https://one.google.com',
    cancellationUrl: 'https://one.google.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Google One > Settings > Cancel membership. Storage reverts to 15GB free.',
  },
  {
    id: 'google-workspace-starter',
    name: 'Google Workspace Business Starter',
    defaultPrice: 700,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'google-workspace',
    url: 'https://workspace.google.com',
    cancellationUrl: 'https://admin.google.com/ac/billing/subscriptions',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Admin console > Billing > Subscriptions > Cancel. Must be admin. Export data first.',
  },
  {
    id: 'icloud-plus-50gb',
    name: 'iCloud+ 50GB',
    defaultPrice: 99,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > iCloud+ > Cancel. Storage reverts to 5GB free.',
  },
  {
    id: 'icloud-plus-200gb',
    name: 'iCloud+ 200GB',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > iCloud+ > Cancel. Storage reverts to 5GB free.',
  },
  {
    id: 'icloud-plus-2tb',
    name: 'iCloud+ 2TB',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'icloud',
    url: 'https://www.apple.com/icloud',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > iCloud+ > Cancel. Storage reverts to 5GB free.',
  },
  {
    id: 'dropbox-plus',
    name: 'Dropbox Plus',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'dropbox',
    url: 'https://www.dropbox.com',
    cancellationUrl: 'https://www.dropbox.com/account/plan',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Plan > Downgrade to Basic. Access continues until billing period ends.',
  },
  {
    id: 'dropbox-professional',
    name: 'Dropbox Professional',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'dropbox',
    url: 'https://www.dropbox.com',
    cancellationUrl: 'https://www.dropbox.com/account/plan',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Plan > Downgrade to Basic. Access continues until billing period ends.',
  },
  {
    id: 'notion-plus',
    name: 'Notion Plus',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'notion',
    url: 'https://www.notion.so',
    cancellationUrl: 'https://www.notion.so/my-account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Plans > Downgrade. Workspace reverts to free tier limits.',
  },
  {
    id: 'evernote-personal',
    name: 'Evernote Personal',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'evernote',
    url: 'https://evernote.com',
    cancellationUrl: 'https://www.evernote.com/Billing.action',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account Settings > Billing > Downgrade. Notes are kept but some features become read-only.',
  },
  {
    id: 'todoist-pro',
    name: 'Todoist Pro',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'todoist',
    url: 'https://todoist.com',
    cancellationUrl: 'https://todoist.com/app/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription. Reverts to free tier.',
  },
  {
    id: 'linear',
    name: 'Linear Standard',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'linear',
    url: 'https://linear.app',
    cancellationUrl: 'https://linear.app/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel plan. Workspace reverts to free tier.',
  },
  {
    id: 'slack-pro',
    name: 'Slack Pro',
    defaultPrice: 875,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'slack',
    url: 'https://slack.com',
    cancellationUrl: 'https://slack.com/intl/en-us/help/articles/218915077',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Workspace Settings > Billing > Cancel plan. Must be workspace owner.',
  },
  {
    id: 'zoom-workplace',
    name: 'Zoom Workplace',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'zoom',
    url: 'https://zoom.us',
    cancellationUrl: 'https://zoom.us/account/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Billing > Cancel subscription. Reverts to free 40-minute limit.',
  },
  {
    id: 'figma-professional',
    name: 'Figma Professional',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'figma',
    url: 'https://www.figma.com',
    cancellationUrl: 'https://www.figma.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Plan > Downgrade to Starter. Existing files are preserved.',
  },
  {
    id: 'canva-pro',
    name: 'Canva Pro',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'canva',
    url: 'https://www.canva.com',
    cancellationUrl: 'https://www.canva.com/settings/billing-and-plans',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account Settings > Billing & plans > Cancel subscription.',
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud All Apps',
    defaultPrice: 5999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-cc',
    url: 'https://www.adobe.com/creativecloud',
    cancellationUrl: 'https://account.adobe.com/plans',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Account > Plans > Cancel plan. Annual plans have an early termination fee (50% of remaining months).',
  },
  {
    id: 'adobe-photography',
    name: 'Adobe Photography Plan',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-cc',
    url: 'https://www.adobe.com/creativecloud/photography',
    cancellationUrl: 'https://account.adobe.com/plans',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Account > Plans > Cancel plan. Annual plans have an early termination fee (50% of remaining months).',
  },
  {
    id: 'adobe-acrobat-pro',
    name: 'Adobe Acrobat Pro',
    defaultPrice: 2299,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'adobe-acrobat',
    url: 'https://www.adobe.com/acrobat',
    cancellationUrl: 'https://account.adobe.com/plans',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Account > Plans > Cancel plan. Annual plans have an early termination fee (50% of remaining months).',
  },
  {
    id: 'grammarly-premium',
    name: 'Grammarly Premium',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'grammarly',
    url: 'https://www.grammarly.com',
    cancellationUrl: 'https://account.grammarly.com/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel subscription. Reverts to free tier.',
  },
  {
    id: '1password',
    name: '1Password',
    defaultPrice: 399,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: '1password',
    url: 'https://1password.com',
    cancellationUrl: 'https://my.1password.com/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel subscription. Export your vault first.',
  },
  {
    id: '1password-family',
    name: '1Password Families',
    defaultPrice: 699,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: '1password',
    url: 'https://1password.com',
    cancellationUrl: 'https://my.1password.com/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel subscription. Export your vault first.',
  },
  {
    id: 'lastpass-premium',
    name: 'LastPass Premium',
    defaultPrice: 300,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'lastpass',
    url: 'https://www.lastpass.com',
    cancellationUrl: 'https://lastpass.com/misc_premium_cancel.php',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account Settings > Subscription > Cancel. Export vault before cancelling.',
  },
  {
    id: 'bitwarden-premium',
    name: 'Bitwarden Premium',
    defaultPrice: 1000,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'bitwarden',
    url: 'https://bitwarden.com',
    cancellationUrl: 'https://vault.bitwarden.com/#/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription. Vault data is preserved.',
  },
  {
    id: 'dashlane-premium',
    name: 'Dashlane Premium',
    defaultPrice: 5328,
    billingCycle: 'annual',
    category: 'productivity',
    iconKey: 'dashlane',
    url: 'https://www.dashlane.com',
    cancellationUrl: 'https://www.dashlane.com/deleteaccount',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel plan. Requires email verification to delete account entirely.',
  },
  {
    id: 'tailscale-personal-pro',
    name: 'Tailscale Personal Pro',
    defaultPrice: 600,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'tailscale',
    url: 'https://tailscale.com',
    cancellationUrl: 'https://login.tailscale.com/admin/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Admin console > Billing > Cancel plan. Reverts to free tier.',
  },
  {
    id: 'superhuman',
    name: 'Superhuman',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'superhuman',
    url: 'https://superhuman.com',
    cancellationUrl: 'https://superhuman.com/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel subscription.',
  },
  {
    id: 'raycast-pro',
    name: 'Raycast Pro',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'raycast',
    url: 'https://www.raycast.com',
    cancellationUrl: 'https://www.raycast.com/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel plan. Reverts to free tier.',
  },
  {
    id: 'setapp',
    name: 'Setapp',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'setapp',
    url: 'https://setapp.com',
    cancellationUrl: 'https://my.setapp.com/account/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Billing > Cancel subscription. All app access ends at billing period.',
  },
  {
    id: 'zapier-starter',
    name: 'Zapier Starter',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'zapier',
    url: 'https://zapier.com',
    cancellationUrl: 'https://zapier.com/app/settings/billing/plans',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Downgrade to Free. Active Zaps are paused.',
  },
  {
    id: 'trello-standard',
    name: 'Trello Standard',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'trello',
    url: 'https://trello.com',
    cancellationUrl: 'https://trello.com/your-boards',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Workspace Settings > Billing > Downgrade to Free. Boards are preserved.',
  },
  {
    id: 'asana-starter',
    name: 'Asana Starter',
    defaultPrice: 1099,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'asana',
    url: 'https://asana.com',
    cancellationUrl: 'https://app.asana.com/admin/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Admin Console > Billing > Downgrade. Must be workspace admin.',
  },
  {
    id: 'monday-standard',
    name: 'monday.com Standard',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'monday',
    url: 'https://monday.com',
    cancellationUrl: 'https://monday.com/admin/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Admin > Billing > Cancel plan. Must be account admin.',
  },
  {
    id: 'miro-starter',
    name: 'Miro Starter',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'miro',
    url: 'https://miro.com',
    cancellationUrl: 'https://miro.com/app/settings/billing/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel plan. Boards become view-only above free tier limits.',
  },
  {
    id: 'obsidian-sync',
    name: 'Obsidian Sync',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'productivity',
    iconKey: 'obsidian',
    url: 'https://obsidian.md',
    cancellationUrl: 'https://obsidian.md/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Local vault is unaffected; sync stops.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // HEALTH (22 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'peloton-app',
    name: 'Peloton App',
    defaultPrice: 1399,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'peloton',
    url: 'https://www.onepeloton.com',
    cancellationUrl: 'https://www.onepeloton.com/settings/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscriptions > Cancel. If via app store, cancel there.',
  },
  {
    id: 'peloton-all-access',
    name: 'Peloton All-Access',
    defaultPrice: 4400,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'peloton',
    url: 'https://www.onepeloton.com',
    cancellationUrl: 'https://www.onepeloton.com/settings/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscriptions > Cancel. If via app store, cancel there.',
  },
  {
    id: 'apple-fitness-plus',
    name: 'Apple Fitness+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'apple-fitness',
    url: 'https://www.apple.com/apple-fitness-plus',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Fitness+ > Cancel.',
  },
  {
    id: 'strava-premium',
    name: 'Strava Premium',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'strava',
    url: 'https://www.strava.com',
    cancellationUrl: 'https://www.strava.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. Activity data is preserved; premium features are locked.',
  },
  {
    id: 'myfitnesspal-premium',
    name: 'MyFitnessPal Premium',
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'myfitnesspal',
    url: 'https://www.myfitnesspal.com',
    cancellationUrl: 'https://www.myfitnesspal.com/account/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscriptions > Cancel Premium. Reverts to free tier.',
  },
  {
    id: 'noom',
    name: 'Noom',
    defaultPrice: 7000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'noom',
    url: 'https://www.noom.com',
    cancellationUrl: 'https://www.noom.com/support/',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Must contact support or use in-app cancellation. Retention offers are common. No straightforward online self-service.',
  },
  {
    id: 'headspace',
    name: 'Headspace',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'headspace',
    url: 'https://www.headspace.com',
    cancellationUrl: 'https://www.headspace.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. If via app store, cancel there.',
  },
  {
    id: 'calm',
    name: 'Calm Premium',
    defaultPrice: 6999,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'calm',
    url: 'https://www.calm.com',
    cancellationUrl: 'https://www.calm.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. If via app store, cancel there.',
  },
  {
    id: 'whoop',
    name: 'WHOOP Membership',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'whoop',
    url: 'https://www.whoop.com',
    cancellationUrl: 'https://app.whoop.com/account/membership',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Account > Membership > Cancel. Annual commitments may require contacting support. Band must be returned if under commitment period.',
  },
  {
    id: 'oura-membership',
    name: 'Oura Membership',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'oura',
    url: 'https://ouraring.com',
    cancellationUrl: 'https://cloud.ouraring.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Basic ring features still work without membership.',
  },
  {
    id: 'fitbit-premium',
    name: 'Fitbit Premium',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'fitbit',
    url: 'https://www.fitbit.com/global/us/technology/premium',
    cancellationUrl: 'https://www.fitbit.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel Fitbit Premium. Basic tracking continues.',
  },
  {
    id: 'nike-training-club',
    name: 'Nike Training Club',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'nike',
    url: 'https://www.nike.com/ntc-app',
    cancellationUrl: 'https://www.nike.com/member/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'If subscribed via app store, cancel in iOS/Android subscription settings.',
  },
  {
    id: 'eight-sleep',
    name: 'Eight Sleep Autopilot',
    defaultPrice: 1900,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'eight-sleep',
    url: 'https://www.eightsleep.com',
    cancellationUrl: 'https://www.eightsleep.com/account',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Membership > Cancel. Temperature control features require active membership.',
  },
  {
    id: 'betterhelp',
    name: 'BetterHelp',
    defaultPrice: 28000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'betterhelp',
    url: 'https://www.betterhelp.com',
    cancellationUrl: 'https://www.betterhelp.com/settings',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Settings > Payment settings > Cancel membership. Multiple retention screens before final cancel.',
  },
  {
    id: 'talkiatry',
    name: 'Talkiatry',
    defaultPrice: 25000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'talkiatry',
    url: 'https://www.talkiatry.com',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Contact your care team or support to cancel. No self-service cancellation page.',
  },
  {
    id: 'cerebral',
    name: 'Cerebral',
    defaultPrice: 9900,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'cerebral',
    url: 'https://cerebral.com',
    cancellationUrl: 'https://cerebral.com/account',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscription > Cancel. Contact support if unable to cancel online.',
  },
  {
    id: 'nurx',
    name: 'Nurx',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'nurx',
    url: 'https://www.nurx.com',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Contact support to cancel. Ensure no pending prescriptions or shipments.',
  },
  {
    id: 'hims',
    name: 'Hims',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'hims',
    url: 'https://www.hims.com',
    cancellationUrl: 'https://www.hims.com/account/subscriptions',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscriptions > Cancel. Multiple confirmation steps. May need to cancel individual prescriptions separately.',
  },
  {
    id: 'hers',
    name: 'Hers',
    defaultPrice: 3000,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'hers',
    url: 'https://www.forhers.com',
    cancellationUrl: 'https://www.forhers.com/account/subscriptions',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscriptions > Cancel. Multiple confirmation steps. May need to cancel individual prescriptions separately.',
  },
  {
    id: 'macrofactor',
    name: 'MacroFactor',
    defaultPrice: 7199,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'macrofactor',
    url: 'https://macrofactorapp.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings. App data is preserved locally.',
  },
  {
    id: 'sleep-cycle-premium',
    name: 'Sleep Cycle Premium',
    defaultPrice: 3999,
    billingCycle: 'annual',
    category: 'health',
    iconKey: 'sleep-cycle',
    url: 'https://www.sleepcycle.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings.',
  },
  {
    id: 'traineroize',
    name: 'TrainerRoad',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'health',
    iconKey: 'trainerroad',
    url: 'https://www.trainerroad.com',
    cancellationUrl: 'https://www.trainerroad.com/app/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Training history is preserved.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SHOPPING (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    defaultPrice: 14999,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'amazon',
    url: 'https://www.amazon.com/prime',
    cancellationUrl: 'https://www.amazon.com/mc/pipelines/cancel-prime',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Prime Membership > End Membership. Multiple retention screens and confirmation steps.',
  },
  {
    id: 'amazon-prime-monthly',
    name: 'Amazon Prime (Monthly)',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'amazon',
    url: 'https://www.amazon.com/prime',
    cancellationUrl: 'https://www.amazon.com/mc/pipelines/cancel-prime',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Prime Membership > End Membership. Multiple retention screens and confirmation steps.',
  },
  {
    id: 'costco-executive',
    name: 'Costco Executive Membership',
    defaultPrice: 13000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'costco',
    url: 'https://www.costco.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel at any Costco membership counter for a full refund, or call 1-800-774-2678.',
  },
  {
    id: 'costco-gold-star',
    name: 'Costco Gold Star Membership',
    defaultPrice: 6500,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'costco',
    url: 'https://www.costco.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel at any Costco membership counter for a full refund, or call 1-800-774-2678.',
  },
  {
    id: 'walmart-plus',
    name: 'Walmart+',
    defaultPrice: 9800,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'walmart',
    url: 'https://www.walmart.com/plus',
    cancellationUrl: 'https://www.walmart.com/account/walmartplus/manage',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Walmart+ > Manage membership > Cancel.',
  },
  {
    id: 'sams-club',
    name: "Sam's Club Membership",
    defaultPrice: 5000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'sams-club',
    url: 'https://www.samsclub.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel at any club membership desk or call 1-888-746-7726. Full refund available anytime.',
  },
  {
    id: 'sams-club-plus',
    name: "Sam's Club Plus Membership",
    defaultPrice: 11000,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'sams-club',
    url: 'https://www.samsclub.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel at any club membership desk or call 1-888-746-7726. Full refund available anytime.',
  },
  {
    id: 'instacart-plus',
    name: 'Instacart+',
    defaultPrice: 9900,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'instacart',
    url: 'https://www.instacart.com',
    cancellationUrl: 'https://www.instacart.com/store/account/instacart-plus',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Instacart+ > Cancel membership.',
  },
  {
    id: 'doordash-dashpass',
    name: 'DoorDash DashPass',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'doordash',
    url: 'https://www.doordash.com/dashpass',
    cancellationUrl: 'https://www.doordash.com/consumer/more/dashpass/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > DashPass > Cancel DashPass.',
  },
  {
    id: 'uber-one',
    name: 'Uber One',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'uber',
    url: 'https://www.uber.com/one',
    cancellationUrl: 'https://www.uber.com/one',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Uber One > Manage membership > Cancel. Also cancellable in the Uber app.',
  },
  {
    id: 'grubhub-plus',
    name: 'Grubhub+',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'grubhub',
    url: 'https://www.grubhub.com',
    cancellationUrl: 'https://www.grubhub.com/help/contact-us',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Grubhub+ membership > Cancel. If bundled with Amazon Prime, cancel through Amazon.',
  },
  {
    id: 'shipt',
    name: 'Shipt Membership',
    defaultPrice: 9900,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'shipt',
    url: 'https://www.shipt.com',
    cancellationUrl: 'https://shop.shipt.com/account/membership',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Membership > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'thrive-market',
    name: 'Thrive Market',
    defaultPrice: 5995,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'thrive-market',
    url: 'https://thrivemarket.com',
    cancellationUrl: 'https://thrivemarket.com/account/membership',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Membership > Cancel. Within 30 days of signup you can get a full refund.',
  },
  {
    id: 'stitch-fix',
    name: 'Stitch Fix',
    defaultPrice: 2000,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'stitch-fix',
    url: 'https://www.stitchfix.com',
    cancellationUrl: 'https://www.stitchfix.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Deliveries > Cancel future Fix deliveries.',
  },
  {
    id: 'rent-the-runway',
    name: 'Rent the Runway',
    defaultPrice: 10000,
    billingCycle: 'monthly',
    category: 'shopping',
    iconKey: 'rent-the-runway',
    url: 'https://www.renttherunway.com',
    cancellationUrl: 'https://www.renttherunway.com/account/membership',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Membership > Cancel. All rented items must be returned before cancellation is final.',
  },
  {
    id: 'aaa-membership',
    name: 'AAA Plus Membership',
    defaultPrice: 12400,
    billingCycle: 'annual',
    category: 'shopping',
    iconKey: 'aaa',
    url: 'https://www.aaa.com',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Call your local AAA club or visit a branch to cancel. No online self-service cancellation.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // NEWS (22 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'nyt-all-access',
    name: 'New York Times All Access',
    defaultPrice: 2500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'nyt',
    url: 'https://www.nytimes.com',
    cancellationUrl: 'https://myaccount.nytimes.com/seg/subscription',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscription > Cancel. Must call or use live chat for some plans. Retention offers common.',
  },
  {
    id: 'nyt-news',
    name: 'New York Times News',
    defaultPrice: 1700,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'nyt',
    url: 'https://www.nytimes.com',
    cancellationUrl: 'https://myaccount.nytimes.com/seg/subscription',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscription > Cancel. Must call or use live chat for some plans. Retention offers common.',
  },
  {
    id: 'washington-post',
    name: 'Washington Post',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wapo',
    url: 'https://www.washingtonpost.com',
    cancellationUrl: 'https://www.washingtonpost.com/my-account/subscriptions/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Subscriptions > Cancel.',
  },
  {
    id: 'wsj',
    name: 'Wall Street Journal',
    defaultPrice: 3999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wsj',
    url: 'https://www.wsj.com',
    cancellationUrl: 'https://customercenter.wsj.com/subscription-cancel',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Customer Center > Cancel Subscription. May require calling customer service.',
  },
  {
    id: 'economist',
    name: 'The Economist',
    defaultPrice: 2900,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'economist',
    url: 'https://www.economist.com',
    cancellationUrl: 'https://myaccount.economist.com/s/subscription',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'My Account > Subscription > Cancel. Phone cancellation may be required for print bundles.',
  },
  {
    id: 'atlantic',
    name: 'The Atlantic',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'atlantic',
    url: 'https://www.theatlantic.com',
    cancellationUrl: 'https://accounts.theatlantic.com/accounts/subscription/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'bloomberg',
    url: 'https://www.bloomberg.com',
    cancellationUrl: 'https://www.bloomberg.com/account/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscriptions > Cancel.',
  },
  {
    id: 'financial-times',
    name: 'Financial Times',
    defaultPrice: 3900,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'ft',
    url: 'https://www.ft.com',
    cancellationUrl: 'https://myaccount.ft.com/details/core/view',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'My Account > Subscription > Cancel. May need to contact support for some plan types.',
  },
  {
    id: 'new-yorker',
    name: 'The New Yorker',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'new-yorker',
    url: 'https://www.newyorker.com',
    cancellationUrl: 'https://www.newyorker.com/my-account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Cancel subscription.',
  },
  {
    id: 'wired',
    name: 'WIRED',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'wired',
    url: 'https://www.wired.com',
    cancellationUrl: 'https://www.wired.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'la-times',
    name: 'Los Angeles Times',
    defaultPrice: 1600,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'la-times',
    url: 'https://www.latimes.com',
    cancellationUrl: 'https://membership.latimes.com/subscription',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscription > Cancel. May require contacting support.',
  },
  {
    id: 'medium',
    name: 'Medium Membership',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'medium',
    url: 'https://medium.com',
    cancellationUrl: 'https://medium.com/me/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Membership > Cancel membership.',
  },
  {
    id: 'substack-pro',
    name: 'Substack (Avg. Paid)',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'substack',
    url: 'https://substack.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Each Substack is cancelled individually from the publication settings page.',
  },
  {
    id: 'apple-news-plus',
    name: 'Apple News+',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'apple-news',
    url: 'https://www.apple.com/apple-news',
    cancellationUrl: 'https://support.apple.com/en-us/118428',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Apple ID > Subscriptions > Apple News+ > Cancel.',
  },
  {
    id: 'the-information',
    name: 'The Information',
    defaultPrice: 39900,
    billingCycle: 'annual',
    category: 'news',
    iconKey: 'the-information',
    url: 'https://www.theinformation.com',
    cancellationUrl: 'https://www.theinformation.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel auto-renewal.',
  },
  {
    id: 'stratechery',
    name: 'Stratechery',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'stratechery',
    url: 'https://stratechery.com',
    cancellationUrl: 'https://stratechery.com/account/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Cancel subscription.',
  },
  {
    id: 'barrons',
    name: "Barron's",
    defaultPrice: 1999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'barrons',
    url: 'https://www.barrons.com',
    cancellationUrl: 'https://customercenter.barrons.com/',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Customer Center > Cancel subscription. May require phone call.',
  },
  {
    id: 'reuters',
    name: 'Reuters',
    defaultPrice: 3500,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'reuters',
    url: 'https://www.reuters.com',
    cancellationUrl: 'https://www.reuters.com/account/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'guardian-supporter',
    name: 'The Guardian Supporter',
    defaultPrice: 1300,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'guardian',
    url: 'https://www.theguardian.com',
    cancellationUrl: 'https://manage.theguardian.com/cancel',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Manage subscription > Cancel. Straightforward self-service.',
  },
  {
    id: 'ars-technica-plus',
    name: 'Ars Technica+',
    defaultPrice: 350,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'ars-technica',
    url: 'https://arstechnica.com',
    cancellationUrl: 'https://arstechnica.com/account/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'the-verge-plus',
    name: 'The Verge (Subscriber)',
    defaultPrice: 700,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'the-verge',
    url: 'https://www.theverge.com',
    cancellationUrl: 'https://www.theverge.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'axios-pro',
    name: 'Axios Pro',
    defaultPrice: 5999,
    billingCycle: 'monthly',
    category: 'news',
    iconKey: 'axios',
    url: 'https://www.axios.com/pro',
    cancellationUrl: 'https://www.axios.com/pro/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // FINANCE (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ynab',
    name: 'YNAB (You Need A Budget)',
    defaultPrice: 10900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'ynab',
    url: 'https://www.ynab.com',
    cancellationUrl: 'https://app.ynab.com/settings/billing',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Billing > Cancel subscription. Budget data is kept for 3 months.',
  },
  {
    id: 'copilot-money',
    name: 'Copilot Money',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'copilot-money',
    url: 'https://copilot.money',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS subscription settings (Apple-only app).',
  },
  {
    id: 'monarch-money',
    name: 'Monarch Money',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'monarch',
    url: 'https://www.monarchmoney.com',
    cancellationUrl: 'https://app.monarchmoney.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'quicken-simplifi',
    name: 'Quicken Simplifi',
    defaultPrice: 4799,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'quicken',
    url: 'https://www.quicken.com/simplifi',
    cancellationUrl: 'https://app.simplifimoney.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel.',
  },
  {
    id: 'quicken-classic',
    name: 'Quicken Classic',
    defaultPrice: 8388,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'quicken',
    url: 'https://www.quicken.com',
    cancellationUrl: 'https://www.quicken.com/support',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Subscription > Turn off auto-renewal. Desktop app continues to work but sync stops.',
  },
  {
    id: 'turbotax-plus',
    name: 'TurboTax Live Assisted',
    defaultPrice: 11900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'turbotax',
    url: 'https://turbotax.intuit.com',
    cancellationUrl: 'https://myturbotax.intuit.com/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'One-time annual purchase; no recurring subscription to cancel for most plans.',
  },
  {
    id: 'credit-karma-plus',
    name: 'Credit Karma Money',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'credit-karma',
    url: 'https://www.creditkarma.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Free service. Delete account via Settings > Account if desired.',
  },
  {
    id: 'personal-capital',
    name: 'Empower Personal Dashboard',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'empower',
    url: 'https://www.empower.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Free dashboard. Advisory services require contacting Empower directly to cancel.',
  },
  {
    id: 'robinhood-gold',
    name: 'Robinhood Gold',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'robinhood',
    url: 'https://robinhood.com/gold',
    cancellationUrl: 'https://robinhood.com/account/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Gold > Downgrade. Margin positions must be closed first.',
  },
  {
    id: 'wealthfront',
    name: 'Wealthfront',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'wealthfront',
    url: 'https://www.wealthfront.com',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Contact support to close account. Investments must be transferred or liquidated first.',
  },
  {
    id: 'betterment-premium',
    name: 'Betterment Premium',
    defaultPrice: 0,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'betterment',
    url: 'https://www.betterment.com',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Contact support to close account. Investments must be transferred or liquidated first.',
  },
  {
    id: 'coinbase-one',
    name: 'Coinbase One',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'coinbase',
    url: 'https://www.coinbase.com/one',
    cancellationUrl: 'https://www.coinbase.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel Coinbase One.',
  },
  {
    id: 'morningstar-premium',
    name: 'Morningstar Investor',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'morningstar',
    url: 'https://www.morningstar.com',
    cancellationUrl: 'https://www.morningstar.com/members/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Settings > Cancel membership.',
  },
  {
    id: 'seeking-alpha-premium',
    name: 'Seeking Alpha Premium',
    defaultPrice: 23900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'seeking-alpha',
    url: 'https://seekingalpha.com',
    cancellationUrl: 'https://seekingalpha.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'motley-fool-stock-advisor',
    name: 'Motley Fool Stock Advisor',
    defaultPrice: 19900,
    billingCycle: 'annual',
    category: 'finance',
    iconKey: 'motley-fool',
    url: 'https://www.fool.com',
    cancellationUrl: 'https://www.fool.com/account/subscription',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > My Services > Cancel. Retention offers are common.',
  },
  {
    id: 'acorns',
    name: 'Acorns Personal',
    defaultPrice: 300,
    billingCycle: 'monthly',
    category: 'finance',
    iconKey: 'acorns',
    url: 'https://www.acorns.com',
    cancellationUrl: 'https://app.acorns.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Close account. Investments are liquidated and deposited to linked bank.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // UTILITIES (16 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'nordvpn',
    name: 'NordVPN',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'nordvpn',
    url: 'https://nordvpn.com',
    cancellationUrl: 'https://my.nordaccount.com/dashboard/nordvpn/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Dashboard > NordVPN > Cancel auto-renewal. Access continues until plan expires.',
  },
  {
    id: 'expressvpn',
    name: 'ExpressVPN',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'expressvpn',
    url: 'https://www.expressvpn.com',
    cancellationUrl: 'https://www.expressvpn.com/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Subscriptions > Turn off auto-renewal. Access continues until plan expires.',
  },
  {
    id: 'surfshark',
    name: 'Surfshark',
    defaultPrice: 1599,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'surfshark',
    url: 'https://surfshark.com',
    cancellationUrl: 'https://my.surfshark.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel auto-renewal. Access continues until plan expires.',
  },
  {
    id: 'protonvpn-plus',
    name: 'ProtonVPN Plus',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'protonvpn',
    url: 'https://protonvpn.com',
    cancellationUrl: 'https://account.proton.me/u/0/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Downgrade to free. VPN access continues until plan expires.',
  },
  {
    id: 'proton-mail-plus',
    name: 'Proton Mail Plus',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'proton-mail',
    url: 'https://proton.me/mail',
    cancellationUrl: 'https://account.proton.me/u/0/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Downgrade to free. Email address is kept.',
  },
  {
    id: 'proton-unlimited',
    name: 'Proton Unlimited',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'proton',
    url: 'https://proton.me',
    cancellationUrl: 'https://account.proton.me/u/0/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Downgrade to free. Reduce storage before downgrading.',
  },
  {
    id: 'mullvad-vpn',
    name: 'Mullvad VPN',
    defaultPrice: 500,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'mullvad',
    url: 'https://mullvad.net',
    cancellationUrl: 'https://mullvad.net/en/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'No auto-renewal. Prepaid time simply expires. No cancellation needed.',
  },
  {
    id: 'backblaze',
    name: 'Backblaze Personal Backup',
    defaultPrice: 900,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'backblaze',
    url: 'https://www.backblaze.com',
    cancellationUrl: 'https://secure.backblaze.com/user_account.htm',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > My Settings > Delete account. Download backups first; data is not recoverable.',
  },
  {
    id: 'carbonite',
    name: 'Carbonite Safe Basic',
    defaultPrice: 7500,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'carbonite',
    url: 'https://www.carbonite.com',
    cancellationUrl: 'https://www.carbonite.com/account',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Turn off auto-renewal or contact support. Backups are deleted after expiration.',
  },
  {
    id: 'idrive',
    name: 'IDrive 5TB',
    defaultPrice: 7995,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'idrive',
    url: 'https://www.idrive.com',
    cancellationUrl: 'https://www.idrive.com/idrive/login/loginForm',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel auto-renewal. Download backups before expiration.',
  },
  {
    id: 'norton-360',
    name: 'Norton 360 Standard',
    defaultPrice: 8999,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'norton',
    url: 'https://us.norton.com',
    cancellationUrl: 'https://my.norton.com/extspa/idsafe?path=subscriptions',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'My Norton > Subscription > Turn off auto-renewal. May require contacting support for refunds.',
  },
  {
    id: 'malwarebytes-premium',
    name: 'Malwarebytes Premium',
    defaultPrice: 4499,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'malwarebytes',
    url: 'https://www.malwarebytes.com',
    cancellationUrl: 'https://my.malwarebytes.com/account/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Subscriptions > Cancel auto-renewal.',
  },
  {
    id: 'cleanmymac',
    name: 'CleanMyMac X',
    defaultPrice: 3995,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'cleanmymac',
    url: 'https://macpaw.com/cleanmymac',
    cancellationUrl: 'https://account.macpaw.com/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'MacPaw Account > Subscriptions > Cancel auto-renewal.',
  },
  {
    id: 'lifelock-standard',
    name: 'LifeLock Standard',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'lifelock',
    url: 'https://www.lifelock.com',
    cancellationUrl: 'https://memberportal.lifelock.com/',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Must call 1-800-543-3562 to cancel. No online self-service cancellation.',
  },
  {
    id: 'aura-identity',
    name: 'Aura Identity Protection',
    defaultPrice: 1200,
    billingCycle: 'monthly',
    category: 'utilities',
    iconKey: 'aura',
    url: 'https://www.aura.com',
    cancellationUrl: 'https://app.aura.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. 60-day money-back guarantee for new subscribers.',
  },
  {
    id: 'deleteme',
    name: 'DeleteMe',
    defaultPrice: 12900,
    billingCycle: 'annual',
    category: 'utilities',
    iconKey: 'deleteme',
    url: 'https://joindeleteme.com',
    cancellationUrl: 'https://joindeleteme.com/help/',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel auto-renewal. Opt-out removals stop at expiration.',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OTHER (26 entries)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'duolingo-plus',
    name: 'Duolingo Super',
    defaultPrice: 1299,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'duolingo',
    url: 'https://www.duolingo.com',
    cancellationUrl: 'https://www.duolingo.com/settings/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel. If via app store, cancel there. Reverts to free tier.',
  },
  {
    id: 'babbel',
    name: 'Babbel',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'babbel',
    url: 'https://www.babbel.com',
    cancellationUrl: 'https://my.babbel.com/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'My Account > Subscription > Cancel. 20-day money-back guarantee for new subscribers.',
  },
  {
    id: 'rosetta-stone',
    name: 'Rosetta Stone',
    defaultPrice: 1199,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'rosetta-stone',
    url: 'https://www.rosettastone.com',
    cancellationUrl: 'https://www.rosettastone.com/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel auto-renewal.',
  },
  {
    id: 'masterclass',
    name: 'MasterClass Standard',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'masterclass',
    url: 'https://www.masterclass.com',
    cancellationUrl: 'https://www.masterclass.com/settings/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscriptions > Cancel membership. 30-day refund available for annual plans.',
  },
  {
    id: 'skillshare-premium',
    name: 'Skillshare Premium',
    defaultPrice: 1400,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'skillshare',
    url: 'https://www.skillshare.com',
    cancellationUrl: 'https://www.skillshare.com/settings/payments',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Payments > Cancel membership.',
  },
  {
    id: 'curiosity-stream',
    name: 'CuriosityStream',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'curiosity-stream',
    url: 'https://curiositystream.com',
    cancellationUrl: 'https://curiositystream.com/settings',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel.',
  },
  {
    id: 'coursera-plus',
    name: 'Coursera Plus',
    defaultPrice: 5900,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'coursera',
    url: 'https://www.coursera.org',
    cancellationUrl: 'https://www.coursera.org/my-purchases',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'My Purchases > Subscriptions > Cancel. 14-day refund policy for annual plans.',
  },
  {
    id: 'linkedin-learning',
    name: 'LinkedIn Learning',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'linkedin',
    url: 'https://www.linkedin.com/learning',
    cancellationUrl: 'https://www.linkedin.com/mypreferences/d/manage-advertising',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Manage Premium subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium Career',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'linkedin',
    url: 'https://www.linkedin.com/premium',
    cancellationUrl: 'https://www.linkedin.com/mypreferences/d/manage-advertising',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Manage Premium subscription > Cancel. Access continues until billing period ends.',
  },
  {
    id: 'bumble-premium',
    name: 'Bumble Premium',
    defaultPrice: 3999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'bumble',
    url: 'https://bumble.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings. No web cancellation available.',
  },
  {
    id: 'tinder-plus',
    name: 'Tinder+',
    defaultPrice: 1499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'tinder',
    url: 'https://tinder.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings. Profile remains active.',
  },
  {
    id: 'tinder-gold',
    name: 'Tinder Gold',
    defaultPrice: 2999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'tinder',
    url: 'https://tinder.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings. Profile remains active.',
  },
  {
    id: 'hinge-preferred',
    name: 'Hinge Preferred',
    defaultPrice: 3499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'hinge',
    url: 'https://hinge.co',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings.',
  },
  {
    id: 'ancestry-plus',
    name: 'Ancestry+',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'ancestry',
    url: 'https://www.ancestry.com',
    cancellationUrl: 'https://www.ancestry.com/account/membership',
    cancellationDifficulty: 'medium',
    cancellationNotes: 'Account > Membership > Cancel renewal. DNA data and tree are preserved. Retention offers common.',
  },
  {
    id: 'find-my-past',
    name: 'FindMyPast',
    defaultPrice: 2499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'findmypast',
    url: 'https://www.findmypast.com',
    cancellationUrl: 'https://www.findmypast.com/account/subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel.',
  },
  {
    id: 'nextdoor',
    name: 'Nextdoor (Ad-Free)',
    defaultPrice: 499,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'nextdoor',
    url: 'https://nextdoor.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings or through the app.',
  },
  {
    id: 'discord-nitro',
    name: 'Discord Nitro',
    defaultPrice: 999,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'discord',
    url: 'https://discord.com/nitro',
    cancellationUrl: 'https://discord.com/settings/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'User Settings > Subscriptions > Cancel. Server boosts are removed at period end.',
  },
  {
    id: 'discord-nitro-basic',
    name: 'Discord Nitro Basic',
    defaultPrice: 299,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'discord',
    url: 'https://discord.com/nitro',
    cancellationUrl: 'https://discord.com/settings/subscriptions',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'User Settings > Subscriptions > Cancel.',
  },
  {
    id: 'snapchat-plus',
    name: 'Snapchat+',
    defaultPrice: 399,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'snapchat',
    url: 'https://www.snapchat.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings.',
  },
  {
    id: 'x-premium',
    name: 'X Premium',
    defaultPrice: 800,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'x',
    url: 'https://x.com',
    cancellationUrl: 'https://x.com/settings/manage_subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription.',
  },
  {
    id: 'x-premium-plus',
    name: 'X Premium+',
    defaultPrice: 1600,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'x',
    url: 'https://x.com',
    cancellationUrl: 'https://x.com/settings/manage_subscription',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Subscription > Cancel subscription.',
  },
  {
    id: 'reddit-premium',
    name: 'Reddit Premium',
    defaultPrice: 599,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'reddit',
    url: 'https://www.reddit.com/premium',
    cancellationUrl: 'https://www.reddit.com/settings/premium',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Premium > Cancel.',
  },
  {
    id: 'patreon-avg',
    name: 'Patreon (Avg. Pledge)',
    defaultPrice: 1000,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'patreon',
    url: 'https://www.patreon.com',
    cancellationUrl: 'https://www.patreon.com/settings/memberships',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Settings > Memberships > Edit pledge > Cancel. Each creator cancelled individually.',
  },
  {
    id: 'bark',
    name: 'Bark Premium (Parental)',
    defaultPrice: 1400,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'bark',
    url: 'https://www.bark.us',
    cancellationUrl: 'https://www.bark.us/account',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Account > Subscription > Cancel subscription.',
  },
  {
    id: 'life360-plus',
    name: 'Life360 Plus',
    defaultPrice: 799,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'life360',
    url: 'https://www.life360.com',
    cancellationDifficulty: 'easy',
    cancellationNotes: 'Cancel via iOS/Android subscription settings. Reverts to free tier.',
  },
  {
    id: 'planet-fitness',
    name: 'Planet Fitness (Classic)',
    defaultPrice: 1500,
    billingCycle: 'monthly',
    category: 'other',
    iconKey: 'planet-fitness',
    url: 'https://www.planetfitness.com',
    cancellationDifficulty: 'hard',
    cancellationNotes: 'Must visit your home club in person or send a certified letter. No online or phone cancellation.',
  },
] as const;

/** Set of entry IDs commonly tracked by users, used for "popular" sorting */
const POPULAR_IDS = new Set([
  'netflix-standard',
  'spotify-premium',
  'youtube-premium',
  'disney-plus',
  'hulu',
  'hbo-max',
  'amazon-prime',
  'apple-tv-plus',
  'apple-music',
  'chatgpt-plus',
  'claude-pro',
  'icloud-plus-200gb',
  'google-one-2tb',
  'microsoft-365-personal',
  '1password',
  'doordash-dashpass',
  'adobe-creative-cloud',
  'ynab',
  'nordvpn',
  'headspace',
]);

/**
 * Returns true if the entry is considered popular.
 */
export function isPopular(entry: CatalogEntry): boolean {
  return POPULAR_IDS.has(entry.id);
}
